import { VitesseThemes } from './colors';

type StyleArgs = ['dark' | 'light'] | ['dark' | 'light', 'soft' | 'black'];

export function getStyle(...args: StyleArgs) {
	const color = colorGetter(...args);
	return {
		border: color('border'),
		'border.variant': color('border'),
		'border.focused': color('border'),
		'border.selected': color('border'),
		'border.transparent': color('border'),
		'border.disabled': color('border'),
		'elevated_surface.background': color('background'),
		'surface.background': color('background'),
		background: color('background'),
		// "element.background": "#2e343eff",
		// "element.hover": "#363c46ff",
		// 'element.active': '#FFFF00',
		// "element.selected": "#454a56ff",
		// "element.disabled": "#2e343eff",
		// "drop_target.background": "#83899480",
		// "ghost_element.background": "#00000000",
		// "ghost_element.hover": "#363c46ff",
		// "ghost_element.active": "#454a56ff",
		// "ghost_element.selected": "#454a56ff",
		// "ghost_element.disabled": "#2e343eff",
		text: color('foreground'),
		// "text.muted": "#a9afbcff",
		// "text.placeholder": "#878a98ff",
		// "text.disabled": "#878a98ff",
		// "text.accent": "#74ade8ff",
		icon: color('foreground'),
		// "icon.muted": "#a9afbcff",
		// "icon.disabled": "#878a98ff",
		// "icon.placeholder": "#a9afbcff",
		// "icon.accent": "#74ade8ff",
		'status_bar.background': color('background'),
		'title_bar.background': color('background'),
		'title_bar.inactive_background': '#FF0000',
		'toolbar.background': color('activeBackground'),
		'tab_bar.background': color('background'),
		'tab.inactive_background': color('background'),
		'tab.active_background': color('activeBackground'),
		'search.match_background': color('activeBackground'),
		'panel.background': color('background'),
		// "panel.focused_border": null,
		// "pane.focused_border": null,
		// "scrollbar.thumb.background": "#c8ccd44c",
		// "scrollbar.thumb.hover_background": "#363c46ff",
		// "scrollbar.thumb.border": "#363c46ff",
		// "scrollbar.track.background": "#00000000",
		// "scrollbar.track.border": "#2e333cff",
		// "link_text.hover": "#74ade8ff",

		'editor.foreground': color('foreground'),
		'editor.background': color('background'),
		'editor.gutter.background': color('background'),
		'editor.subheader.background': color('background'),
		'editor.active_line.background': color('background'),
		'editor.highlighted_line.background': color('background'),
		'editor.line_number': color('foreground'),
		'editor.active_line_number': color('activeForeground'),
		'editor.invisible': color('selectionBackground'),
		'editor.wrap_guide': '#FF0000',
		'editor.active_wrap_guide': '#FF0000',
		'editor.document_highlight.read_background': color('activeBackground'),
		'editor.document_highlight.write_background': '#FF0000',

		'terminal.background': color('background'),
		'terminal.foreground': color('foreground'),
		'terminal.bright_foreground': '#FF0000',
		'terminal.dim_foreground': '#FF0000',
		'terminal.ansi.black': args[0] === 'dark' ? color('foreground') : color('background'),
		'terminal.ansi.bright_black': args[0] === 'dark' ? '#777777' : '#aaaaaa',
		'terminal.ansi.dim_black': args[0] === 'dark' ? '#777777' : '#aaaaaa',
		'terminal.ansi.red': color('red'),
		'terminal.ansi.bright_red': color('red'),
		'terminal.ansi.dim_red': color('red'),
		'terminal.ansi.green': color('green'),
		'terminal.ansi.bright_green': color('green'),
		'terminal.ansi.dim_green': color('green'),
		'terminal.ansi.yellow': color('yellow'),
		'terminal.ansi.bright_yellow': color('yellow'),
		'terminal.ansi.dim_yellow': color('yellow'),
		'terminal.ansi.blue': color('blue'),
		'terminal.ansi.bright_blue': color('blue'),
		'terminal.ansi.dim_blue': color('blue'),
		'terminal.ansi.magenta': color('magenta'),
		'terminal.ansi.bright_magenta': color('magenta'),
		'terminal.ansi.dim_magenta': color('magenta'),
		'terminal.ansi.cyan': color('cyan'),
		'terminal.ansi.bright_cyan': color('cyan'),
		'terminal.ansi.dim_cyan': color('cyan'),
		'terminal.ansi.white': '#dbd7ca',
		'terminal.ansi.bright_white': '#dbd7ca',
		'terminal.ansi.dim_white': '#dbd7ca',

		conflict: color('orange'),
		'conflict.background': null,
		'conflict.border': null,
		created: color('green'),
		'created.background': null,
		'created.border': null,
		deleted: color('red'),
		'deleted.background': null,
		'deleted.border': null,
		error: color('red'),
		'error.background': null,
		'error.border': null,
		hidden: '#FF0000',
		'hidden.background': null,
		'hidden.border': null,
		hint: color('green'),
		'hint.background': null,
		'hint.border': null,
		ignored: color('ignored'),
		'ignored.background': null,
		'ignored.border': null,
		info: color('blue'),
		'info.background': null,
		'info.border': null,
		modified: color('blue'),
		'modified.background': null,
		'modified.border': null,
		predictive: '#FF0000',
		'predictive.background': null,
		'predictive.border': null,
		renamed: '#74ade8ff',
		'renamed.background': '#74ade81a',
		'renamed.border': '#293b5bff',
		success: color('green'),
		'success.background': null,
		'success.border': null,
		unreachable: '#FF0000',
		'unreachable.background': null,
		'unreachable.border': null,
		warning: color('orange'),
		'warning.background': null,
		'warning.border': null,

		players: [
			{
				cursor: color('foreground'),
				background: color('foreground'),
				selection: color('selectionBackground'),
			},
			//   {
			//     cursor: "#be5046ff",
			//     background: "#be5046ff",
			//     selection: "#be50463d",
			//   },
			//   {
			//     cursor: "#bf956aff",
			//     background: "#bf956aff",
			//     selection: "#bf956a3d",
			//   },
			//   {
			//     cursor: "#b477cfff",
			//     background: "#b477cfff",
			//     selection: "#b477cf3d",
			//   },
			//   {
			//     cursor: "#6eb4bfff",
			//     background: "#6eb4bfff",
			//     selection: "#6eb4bf3d",
			//   },
			//   {
			//     cursor: "#d07277ff",
			//     background: "#d07277ff",
			//     selection: "#d072773d",
			//   },
			//   {
			//     cursor: "#dec184ff",
			//     background: "#dec184ff",
			//     selection: "#dec1843d",
			//   },
			//   {
			//     cursor: "#a1c181ff",
			//     background: "#a1c181ff",
			//     selection: "#a1c1813d",
			//   },
		],

		syntax: {
			attribute: syntax(color('variable')),
			boolean: syntax(color('boolean')),
			comment: syntax(color('comment')),
			'comment.doc': syntax(color('comment')),
			constant: syntax(color('constant')),
			constructor: syntax(color('keyword')),
			embedded: syntax('#FF0000'),
			emphasis: syntax('#FF0000'),
			'emphasis.strong': syntax('#FF0000'),
			enum: syntax('#FF0000'),
			function: syntax(color('function')),
			hint: syntax('#FF0000'),
			keyword: syntax(color('operator')),
			label: syntax(color('keyword')),
			link_text: syntax('#FF0000'),
			link_uri: syntax('#FF0000'),
			number: syntax(color('number')),
			operator: syntax(color('operator')),
			predictive: syntax('#FF0000'),
			preproc: syntax('#FF0000'),
			primary: syntax(color('primary')),
			property: syntax(color('property')),
			punctuation: syntax(color('punctuation')),
			'punctuation.bracket': syntax(color('punctuation')),
			'punctuation.delimiter': syntax(color('punctuation')),
			'punctuation.list_marker': syntax(color('punctuation')),
			'punctuation.special': syntax(color('punctuation')),
			string: syntax(color('string')),
			'string.escape': syntax(color('string')),
			'string.regex': syntax(color('string')),
			'string.special': syntax(color('string')),
			'string.special.symbol': syntax(color('string')),
			tag: syntax('#FF0000'),
			'text.literal': syntax('#FF0000'),
			title: syntax('#FF0000'),
			type: syntax(color('type')),
			variable: syntax(color('variable')),
			'variable.special': syntax(color('variable')),
			variant: syntax('#FF0000'),
		},
	};
}

function colorGetter(...args: StyleArgs) {
	return (key: keyof typeof VitesseThemes) => {
		if (args.length === 2) {
			const variantKey = args[1] + key[0].toUpperCase() + key.slice(1);
			if (variantKey in VitesseThemes) {
				key = variantKey as keyof typeof VitesseThemes;
			}
		}
		return VitesseThemes[key][args[0] === 'dark' ? 0 : 1];
	};
}

function syntax(color: string) {
	return { color, font_style: null, font_weight: null };
}
